// A read-only fitting room: preview changes never edit a real player's appearance.
function hairFitPreview(){
 if(!charsReady)return;
 note('머리카락 위치 수정 전·후','<p>위: 얼굴 비율에 맞춘 이전 배치 · 아래: 체형별 모자 경계에 맞춘 새 배치</p><label>머리카락 <select id="hairFitChoice">'+CharacterRenderer.variants.hair.map((n,i)=>'<option value="'+i+'" '+(i===4?'selected':'')+'>'+n+'</option>').join('')+'</select></label><canvas id="hairFitCanvas" width="1320" height="620" style="width:100%;image-rendering:pixelated"></canvas>');
 $('#dialog').style.cssText='max-width:1400px;width:96vw';
 const draw=()=>{const cv=$('#hairFitCanvas'),g=cv.getContext('2d');g.imageSmoothingEnabled=false;g.fillStyle='#dbe5dd';g.fillRect(0,0,1320,620);for(let row=0;row<2;row++)for(let body=0;body<6;body++){const p=clone(demoPlayer);p.id='hair-fit-'+row+'-'+body;p.appearance={version:12,legacyHair:row===0,body,skin:0,hairColor:2,eyeColor:0,parts:{hair:+$('#hairFitChoice').value,beard:2,wear:1,black:0,eyes:0,nose:3,brows:0,mouth:0}};const out=charFrame(p,{primary:4,secondary:3},'detail'),f=out.face;g.fillStyle=row?'#254d40':'#714b48';g.font='17px Galmuri9';g.fillText((row?'수정 후 · ':'수정 전 · ')+LAB_DATA.bodies[body].name,body*220+8,row*310+28);g.drawImage(out.canvas,f[0]-f[2]*.32,f[1]-f[3]*.82,f[2]*1.64,f[3]*2.3,body*220+7,row*310+45,206,255);}};
 $('#hairFitChoice').onchange=draw;draw();
}
function characterPreview(){
 const controls=['hair','beard','wear','black'].map(k=>'<label>'+CharacterRenderer.names[k]+' <select data-look="'+k+'"><option value="-1">없음</option>'+CharacterRenderer.variants[k].map((n,i)=>'<option value="'+i+'" '+((k==='hair'&&i===4)?'selected':'')+'>'+n+'</option>').join('')+'</select></label>').join('');
 note('선수 외형 미리보기','<p>각 줄은 다른 체형입니다. 경기 자세 6개와 상세 얼굴을 함께 비교합니다. 실제 선수는 바뀌지 않습니다.</p><div class="look-controls">'+controls+'<label>동작 <select id="lookAction">'+['타격','투구','포구·송구','주루','다이빙·슬라이딩','타석 반응'].map((n,i)=>'<option value="'+i+'">'+n+'</option>').join('')+'</select></label><label><input type="checkbox" id="lookFlip"> 좌우 반전</label></div><canvas id="lookCanvas" width="1200" height="900" style="width:100%;height:auto;image-rendering:pixelated"></canvas>');
 $('#dialog').style.maxWidth='1250px';$('#dialog').style.width='94vw';$('.look-controls').style.cssText='display:flex;flex-wrap:wrap;gap:8px 16px;align-items:center;margin-bottom:12px';
 const draw=()=>{const cv=$('#lookCanvas');if(!cv)return;const g=cv.getContext('2d');g.imageSmoothingEnabled=false;g.fillStyle='#dce7df';g.fillRect(0,0,1200,900);const row=+$('#lookAction').value,parts=Object.fromEntries($$('[data-look]').map(n=>[n.dataset.look,+n.value]));for(let body=0;body<6;body++){const p=clone(demoPlayer);p.id='fitting-'+body;p.appearance={version:12,body,skin:0,hairColor:2,eyeColor:0,parts:{eyes:0,nose:3,brows:0,mouth:0,...parts}};const tm={primary:4,secondary:3};const yy=body*150;g.fillStyle=body%2?'#bed4c4':'#d2e1d6';g.fillRect(0,yy,1200,150);g.fillStyle='#193247';g.font='16px Galmuri9';g.fillText(LAB_DATA.bodies[body].name,12,yy+23);for(let col=0;col<6;col++){const a=charFrame(p,tm,'motion',row,col),s=100/a.standHeight;g.save();g.translate(175+col*150,yy+140);if($('#lookFlip').checked)g.scale(-1,1);g.drawImage(a.canvas,-a.anchorX*s,-a.anchorY*s,a.canvas.width*s,a.canvas.height*s);g.restore();}const a=charFrame(p,tm,'detail'),f=a.face;g.drawImage(a.canvas,f[0]-f[2]*.25,f[1]-f[3]*.70,f[2]*1.5,f[3]*2,1080,yy+15,108,130);}};
 $$('.look-controls select,.look-controls input').forEach(n=>n.addEventListener('change',draw));draw();
}
const lookRenderBase=render;render=function(){lookRenderBase();if(screen==='settings'&&team())$('#app').insertAdjacentHTML('beforeend','<section class="panel"><h3>선수 외형</h3><p>여섯 체형의 경기 자세와 상세 얼굴을 함께 확인합니다.</p><button data-look-open>선수 외형 미리보기</button></section>');};
document.addEventListener('click',ev=>{if(ev.target.closest('[data-look-open]')&&charsReady)characterPreview();if(ev.target.closest('[data-hair-fit]'))hairFitPreview();});

if(new URLSearchParams(location.search).get('qa')==='1'){
 const bar=document.createElement('section');bar.id='qaTools';bar.style.cssText='position:fixed;bottom:0;left:0;right:0;padding:8px;background:#061a2feb;z-index:90;font:12px sans-serif;max-height:40vh;overflow:auto';bar.innerHTML='<button id="qaRun">규칙·216자세 검사</button> <button data-look-open>선수 외형 미리보기</button> <button data-hair-fit>머리카락 수정 전·후</button><pre id="qaReport" style="white-space:pre-wrap"></pre>';document.body.append(bar);
 $('#qaRun').onclick=async()=>{if(!charsReady)return;const report=$('#qaReport');report.textContent='검사 중…';const before=JSON.stringify(data);const checks=ruleChecks();let poses=0,variants=0;const errors=[];try{for(let body=0;body<6;body++){const p=clone(demoPlayer);p.id='qa-'+body;p.appearance={version:12,body,skin:0,hairColor:2,eyeColor:1,parts:{hair:4,beard:2,wear:0,black:0,eyes:0,nose:3,brows:0,mouth:0}};const tm={primary:4,secondary:3};for(let row=0;row<6;row++)for(let col=0;col<6;col++){const out=charFrame(p,tm,'motion',row,col);if(!out.canvas.width||!out.canvas.height||!out.rects.hair)throw Error('자세 누락 '+[body,row,col]);if(Object.values(out.rects).flat().some(n=>!Number.isFinite(n)))throw Error('좌표 오류');poses++;}for(const kind of ['hair','beard','wear','black'])for(let index=0;index<CharacterRenderer.variants[kind].length;index++){p.appearance.parts[kind]=index;for(const mode of ['detail','motion']){const out=charFrame(p,tm,mode,1,0);if(!out.rects[kind])throw Error('파츠 누락 '+[body,kind,index,mode]);}variants++;}await new Promise(requestAnimationFrame);}
 }catch(e){errors.push(e.message);}if(JSON.stringify(data)!==before)errors.push('검사 전후 저장 내용 불일치');const result={rulesPassed:checks.filter(x=>x.ok).length,rulesTotal:checks.length,ruleFailures:checks.filter(x=>!x.ok),poses,bodyVariantPairs:variants,errors,runtimeErrors:runtimeErrors.slice(),assets:CharacterRenderer.diagnostics()};window.characterQA=result;report.textContent=JSON.stringify(result,null,2);};
}
