function checks26(){const keep={selection,activeGame};try{return context23(()=>{
 const rows=[],check=(name,fn)=>{try{if(!fn())throw Error('기대 결과와 다름');rows.push({name,ok:true});}catch(e){rows.push({name,ok:false,error:e.stack});}};
 const fixture=()=>{const f=fixture23();f.t.balance.fanEventChance=0;f.t.funds=1000000;f.t.debt=0;f.t.players.forEach(p=>{p.wage26={ask:100,baseline:clone(p.stats),clubGames:0,expired:false,lastChange:null};p.salary=100;p.contract=8;p.loyalty=60;});return f;};
 check('희망급여 90% 이하는 -3 · 복지로 상쇄하지 않음',()=>{const {t,m}=fixture(),p=t.players[0];p.salary=90;settleContract26(t,p,m,3);return p.loyalty===57&&m.wageEffects26[0].wageDelta===-3;});
 check('91%와 119%는 급여 애정도 변화 없음',()=>{const {t,m}=fixture(),p=t.players[0];for(const n of [91,100,119]){p.salary=n;settleContract26(t,p,m,0);}return p.loyalty===60;});
 check('120% 상승확률 100%/0% 경계',()=>{const {t,m}=fixture(),p=t.players[0];p.salary=120;t.balance.salaryBonusChance=1;settleContract26(t,p,m,0);t.balance.salaryBonusChance=0;settleContract26(t,p,m,0);return p.loyalty===61;});
 check('기본 확률 30% · 2000회 분포와 상한',()=>{const {t,m}=fixture(),p=t.players[0];p.salary=120;let count=0;for(let i=0;i<2000;i++){p.loyalty=60;p.contract=8;settleContract26(t,p,m,0);if(p.loyalty===61)count++;}p.loyalty=100;t.balance.salaryBonusChance=1;settleContract26(t,p,m,0);return count>480&&count<720&&p.loyalty===100;});
 check('계약 중 능력·애정도 변화에도 희망급여 고정',()=>{const {t}=fixture(),p=t.players[0];p.loyalty=12;p.a.power=100;return salaryAsk(p)===100;});
 check('활약과 출전으로 계약 만료 때만 재산정',()=>{const {t,m}=fixture(),p=t.players[0];p.contract=2;t.w=7;p.stats.games=7;p.stats.pa=28;p.stats.ab=25;p.stats.h=15;p.stats.hr=5;p.stats.bb=3;settleContract26(t,p,m,0);const held=salaryAsk(p)===100;t.w++;settleContract26(t,p,m,0);const changed=salaryAsk(p)>100&&salaryAsk(p)<=120&&p.wage26.lastChange.games===7;const ask=salaryAsk(p);settleContract26(t,p,m,0);return held&&changed&&salaryAsk(p)===ask;});
 check('저활약·미출전 선수 희망급여 하락도 가능',()=>{const {t}=fixture(),p=t.players[0];p.wage26.ask=1000;t.w=8;renewAsk26(t,p);return salaryAsk(p)<1000&&salaryAsk(p)>=800;});
 check('80% 제안 수락 · 즉시 애정도 보너스 없음',()=>{const {t}=fixture(),p=t.players[0];t.match=null;const result=negotiate(p,80);return result==='재계약했습니다.'&&p.salary===80&&p.loyalty===60&&!p.wage26.expired;});
 check('낮은 제안으로 애정도 0이면 12명도 즉시 이적',()=>{const {t}=fixture(),p=t.players[0];t.match=null;p.loyalty=15;const id=p.id;negotiate(p,79);return t.players.length===11&&!t.players.some(x=>x.id===id)&&t.departed.some(x=>x.id===id)&&!lineupError(t);});
 check('9명 중 이적 → 8명과 빈 타순 저장·복원',()=>{const {t}=fixture();t.match=null;t.players=t.players.slice(0,9);t.players[0].loyalty=0;departUnhappy26(t);validateTeam(clone(t));return t.players.length===8&&t.lineup.filter(x=>!x.id).length===1&&validVacancy26(t);});
 check('전원 이적 후에도 관리·훈련·홈·협상 화면 생성',()=>{const {t}=fixture();t.match=null;t.players.forEach(p=>p.loyalty=0);departUnhappy26(t);validateTeam(clone(t));return !t.players.length&&[playersArtworkHTML(t),growthArtworkHTML(t),homeArtworkHTML(t),financeHTML(t)].every(x=>typeof x==='string'&&x.length>0);});
 check('경기 정산에서 0 이적 · 기존 경기 선수와 기록 보존',()=>{const {t,m}=fixture(),p=t.players[0];p.loyalty=3;p.salary=90;const id=p.id;m.done=true;m.score=[4,3];reward(m);validateTeam(clone(t));const ok=t.players.length===11&&t.departed.some(x=>x.id===id)&&tside(m,0).players.some(x=>x.id===id)&&t.history.length===1;const state=JSON.stringify(t);reward(m);return ok&&state===JSON.stringify(t);});
 check('계약 자료 저장·복원과 9명 미만 영입 가능',()=>{const {t}=fixture();t.match=null;t.players=t.players.slice(0,9);t.players[0].loyalty=0;departUnhappy26(t);refreshMarket(t);const c=clone(t);validateTeam(c);return c.players[0].wage26.ask===100&&c.market.length===3;});
 check('홈 선수 장식과 기대주 제거',()=>{const {t}=fixture();return !homeArtworkHTML(t).includes('clubCast')&&!homeArtworkHTML(t).includes('기대주');});
 check('관리 상세 캐릭터·접히는 기록·협상 연결',()=>{const {t}=fixture();const html=playersArtworkHTML(t);return html.includes('data-portrait')&&html.includes('<details')&&html.includes('data-contract-finance')&&financeHTML(t).includes('data-contract-profile');});
 return {checks:rows,passed:rows.filter(x=>x.ok).length,total:rows.length,runtimeErrors:runtimeErrors.slice()};
 });}finally{selection=keep.selection;activeGame=keep.activeGame;}}
if($('#qaTools')){
 const b=document.createElement('button');b.textContent='계약·이적 규칙 검사';b.onclick=()=>note('계약·이적 규칙 검사','<pre id="report26">'+esc(JSON.stringify(checks26(),null,2))+'</pre>');$('#qaTools').append(b);
 const f=document.createElement('button');f.textContent='계약·선수관리 테스트 구단';f.onclick=()=>{if(!f.dataset.active){suppressPersist++;f.dataset.active='true';}const {t}=fixture23();t.match=null;t.funds=100000;t.name='해체 드림즈';t.players.forEach((p,i)=>{p.appearance.body=i%6;p.wage26={ask:100,baseline:clone(p.stats),clubGames:0,expired:false,lastChange:null};p.salary=i%3===0?120:i%3===1?90:100;p.contract=8;p.loyalty=60;});activeGame=true;selection=t.players[0].id;screen='players';render();toast('저장하지 않는 테스트 구단입니다.');};$('#qaTools').append(f);
}
