// Integrated v08. All numeric management rules below are editable trial values.
const BALANCE={startFunds:3000,facilityPrice:1000,maintenance:150,baseReward:350,runReward:80,winReward:600,hireFactor:35,trainingFactor:110,salaryFactor:4,contractGames:5,ticketBase:10,pitchCost:1.2,swingCost:.8,powerCost:1.6,runCost:.025,fatigueFloor:.35,staminaCap:100,fanEventChance:.32};
const BALANCE_LABELS={startFunds:'새 구단 시작 자금',facilityPrice:'기본 시설 건설비',maintenance:'시설당 경기 유지비',baseReward:'경기 완료 자금',runReward:'득점당 자금',winReward:'승리 추가 자금',hireFactor:'영입 계수 · 평균² ÷50에 곱함',trainingFactor:'성장 구간당 기본 비용',salaryFactor:'급여 계수 · 평균² ÷50에 곱함',contractGames:'계약 경기 수',ticketBase:'기준 입장료',pitchCost:'투구 체력 소모',swingCost:'일반 스윙 체력 소모',powerCost:'풀스윙 체력 소모',runCost:'이동 거리당 체력 소모',fatigueFloor:'최저 체력의 능력 비율',staminaCap:'시험 스태미나 성장 한도',fanEventChance:'경기 후 팬 사건 확률'};
STATS.stamina='스태미나';KEYS.push('stamina');
function balance(t=team()){return {...BALANCE,...t?.balance};}
function meanAbility(p){return KEYS.filter(k=>k!=='stamina').reduce((s,k)=>s+p.a[k],0)/9;}
function abilityPrice(p){return meanAbility(p)**2/50;}
function adjustEconomy(t){if(!t||t.economyVersion===9||t.match&&!t.match.done)return;
 t.balance={...BALANCE,...t.balance,maintenance:150,hireFactor:35,trainingFactor:110,salaryFactor:4};
 t.players.forEach(p=>p.salary=Math.max(3,Math.round(abilityPrice(p)*t.balance.salaryFactor)));
 (t.market||[]).forEach(p=>{p.salary=Math.max(3,Math.round(abilityPrice(p)*t.balance.salaryFactor));p.price=Math.round(abilityPrice(p)*t.balance.hireFactor);});
 t.economyVersion=9;t.economyNotice=true;
}
function operatingBudget(t){const salary=t.players.reduce((n,p)=>n+p.salary,0),maintenance=t.facilities.length*balance(t).maintenance;return {salary,maintenance,total:salary+maintenance};}
function budgetHTML(t){const b=balance(t),o=operatingBudget(t),gate=attendance(t)*t.ticket,shops=attendance(t)*t.facilities.filter(x=>['goods','restaurant','store'].includes(x)).length,loss=b.baseReward+3*b.runReward+(gate+shops)/2-o.total;
return '<section class="panel settings-extra"><h3>다음 경기 운영비</h3><div class="row between"><span>선수 '+t.players.length+'명 급여</span><b>'+money(o.salary)+'</b></div><div class="row between"><span>시설 '+t.facilities.length+'개 유지비</span><b>'+money(o.maintenance)+'</b></div><div class="row between"><strong>매 경기 고정 지출</strong><strong class="bad">'+money(o.total)+'</strong></div><p class="muted-note">홈·원정 반반, 경기당 3득점 가정 · 경기당 예상 손익<br>패배 '+(loss>=0?'+':'')+money(loss)+' / 승리 '+(loss+b.winReward>=0?'+':'')+money(loss+b.winReward)+'<br>관중·득점·시설·선수단에 따라 달라집니다. 현재 미지급금은 별도 '+money(t.debt)+'.</p>'+(t.funds<o.total?'<p class="bad">보유 자금이 1경기 운영비보다 적습니다. 추가 투자 전 결산을 확인하세요.</p>':'')+'</section>';
}
function appearance(){return {version:12,body:randomInt(0,5),skin:randomInt(0,5),hairColor:randomInt(1,6),eyeColor:randomInt(0,5),parts:{hair:Math.random()<.3?-1:randomInt(0,6),beard:Math.random()<.65?-1:randomInt(0,4),wear:Math.random()<.7?-1:randomInt(0,5),black:Math.random()<.65?-1:randomInt(0,2),eyes:randomInt(0,5),nose:randomInt(0,5),brows:randomInt(0,5),mouth:randomInt(0,5)}};}
function migrateAppearance(a){if(!a)return;if(!a.parts)a.parts={};const p=a.parts;if(a.version!==12){if(p.beard>=0)p.beard=[4,0,1,2,3][p.beard]??p.beard;if(p.wear>=0)p.wear=[0,1,4,5][p.wear]??p.wear;if(p.brows>=0)p.brows=[0,1,4,2,3,5,5][p.brows]??p.brows;a.version=12;}p.black??=-1;}

function enrich(p){p.appearance??=appearance();migrateAppearance(p.appearance);p.a.stamina??=randomInt(40,80);p.energy??=p.a.stamina;p.loyalty??=randomInt(45,70);p.fans??=randomInt(15,85);p.salary??=Math.max(3,Math.round(abilityPrice(p)*balance().salaryFactor));p.contract??=balance().contractGames;p.lowOffers??=0;return p;}
const oldPlayer=player;player=function(...args){const p=oldPlayer(...args);p.a.stamina=randomInt(40,80);return enrich(p);};
function ensureClub(t){if(!t)return;t.funds??=BALANCE.startFunds;t.balance??={...BALANCE};t.facilities??=[];t.stadium??=1;t.ticket??=10;t.debt??=0;t.ledger??=[];t.news??=[];t.departed??=[];t.market??=[];t.players.forEach(enrich);if(t.match?.opp){t.match.opp.players.forEach(enrich);t.match.used??=t.lineup.map(x=>x.id);t.match.subs??=[];}t.coins=0;t.trophies=t.w;adjustEconomy(t);}
const oldNewTeam=newTeam;newTeam=function(...args){const t=oldNewTeam(...args);ensureClub(t);t.players.forEach((p,i)=>p.appearance.body=i%6);return t;};
const oldInitial=ensureInitialRoster;ensureInitialRoster=function(t){const empty=!t.players.length;oldInitial(t);ensureClub(t);if(empty)t.players.forEach((p,i)=>p.appearance.body=i%6);};
const originalGo=go;go=function(where){if(activeGame&&needsSetup(team())&&['market','facilities','finance','news'].includes(where)){toast('먼저 시작 선수 12명의 이름·등번호와 라인업을 정해 주세요.');where='setup';}originalGo(where);};
ensurePlayerLooks=function(t){if(!t?.players)return;t.players.forEach(enrich);if(t.match?.opp)ensurePlayerLooks(t.match.opp);};
const oldValidate=validateTeam;validateTeam=function(t){t.players.forEach(p=>migrateAppearance(p.appearance));oldValidate(t);if(!Number.isFinite(t.funds)||t.funds<0||!Array.isArray(t.facilities)||!Number.isInteger(t.stadium)||t.stadium<1||t.stadium>5||!Number.isFinite(t.debt)||t.debt<0)throw Error('v08 구단 자료가 아닙니다. 이전 저장 원본은 이전 버전에서 열어주세요.');for(const p of t.players){const a=p.appearance;if(!a||!Number.isInteger(a.body)||a.body<0||a.body>5||!Number.isFinite(p.energy)||p.energy<0||p.energy>p.a.stamina||!Number.isFinite(p.salary)||p.salary<0||!Number.isInteger(p.contract)||p.contract<0||!Number.isFinite(p.loyalty)||p.loyalty<0||p.loyalty>100||!Number.isFinite(p.fans)||p.fans<0)throw Error('선수 체력·외형·계약 자료 오류');for(const k of Object.keys(CharacterRenderer.names)){const v=a.parts?.[k];if(!Number.isInteger(v)||v< -1||v>=CharacterRenderer.variants[k].length)throw Error('외형 파츠 자료 오류');}}for(const [k,v]of Object.entries(t.balance||{}))if(!(k in BALANCE)||!Number.isFinite(v)||v<0||v>100000)throw Error('시험 설정 오류');};
const FACILITIES=[['bat','타격 훈련실','컨택 · 파워 · 선구안 성장',['contact','power','eye'],'훈련'],['field','수비 훈련실','야구센스 · 포구 · 송구 성장',['sense','catch','throw'],'훈련'],['pitch','투수 훈련실','구속 · 제구 성장',['velocity','control'],'훈련'],['run','달리기장','주력 성장',['speed'],'훈련'],['fitness','체력 훈련실','스태미나 성장',['stamina'],'훈련'],['shower','샤워실','경기 후 애정도 +1',[],'복지'],['locker','탈의실','경기 후 애정도 +1',[],'복지'],['massage','마사지실','경기 후 애정도 +1',[],'복지'],['sleep','수면실','경기 후 애정도 +1',[],'복지'],['food','선수 식당','경기 후 애정도 +1',[],'복지'],['goods','유니폼 · 굿즈 매장','홈 관중 1명당 추가 수입 1,000원',[],'수익'],['restaurant','구장 음식점','홈 관중 1명당 추가 수입 1,000원',[],'수익'],['store','편의점','홈 관중 1명당 추가 수입 1,000원',[],'수익'],['fans','팬 만남 광장','경기 후 모든 선수 팬 +2',[],'팬']];
const WON_PER_UNIT=10000,TICKET_WON_PER_UNIT=1000,SPECTATORS_PER_UNIT=10;
const wonValue=n=>Math.round(n*WON_PER_UNIT);
function formatWon(value){const n=Math.abs(Math.round(value)),sign=value<0?'-':'',eok=Math.floor(n/100000000),man=Math.floor(n%100000000/10000),won=n%10000,parts=[];if(eok)parts.push(eok.toLocaleString('ko-KR')+'억');if(man)parts.push(man.toLocaleString('ko-KR')+'만');if(won)parts.push(won.toLocaleString('ko-KR'));return sign+(parts.length?parts.join(' ')+' 원':'0원');}
const money=n=>formatWon(wonValue(n));
const spectators=n=>Math.round(n*SPECTATORS_PER_UNIT).toLocaleString('ko-KR');
const ticketInput=n=>n*TICKET_WON_PER_UNIT;
const ticketFromInput=n=>Number(n)/TICKET_WON_PER_UNIT;
const salaryFromInput=n=>Number(n)/WON_PER_UNIT;
function balanceUnit(k){return k==='ticketBase'?TICKET_WON_PER_UNIT:['startFunds','facilityPrice','maintenance','baseReward','runReward','winReward','hireFactor','trainingFactor','salaryFactor'].includes(k)?WON_PER_UNIT:1;}

const live=t=>!!(t?.match&&!t.match.done);
function ledger(t,label,amount){t.ledger.unshift({at:Date.now(),label,amount});t.ledger=t.ledger.slice(0,150);}
function spend(t,price,label){if(!Number.isFinite(price)||price<0||t.funds<price)return false;t.funds-=price;ledger(t,label,-price);return true;}
function gain(t,amount,label){if(amount<0||!Number.isFinite(amount))throw Error('잘못된 수입');t.funds+=amount;ledger(t,label,amount);}
function news(t,title,text){t.news.unshift({at:Date.now(),title,text});t.news=t.news.slice(0,50);}
function attendance(t){const b=balance(t),cap=t.stadium*200,pop=t.players.reduce((s,p)=>s+p.fans,0)*.3+80;return Math.round(clamp(pop*(b.ticketBase/Math.max(1,t.ticket))**1.8,0,cap));}
function costGrowth(p,k){const b=balance();return p.a[k]>=(k==='stamina'?b.staminaCap:100)?0:cost(p.a[k])*b.trainingFactor;}
function trainingFacility(k){return FACILITIES.find(f=>f[3].includes(k));}
function energyHTML(p){const pct=Math.round(100*p.energy/p.a.stamina);return '<span class="energy"><i style="width:'+pct+'%;background:'+(pct<25?'#ff736f':'#68d2a4')+'"></i></span><small>체력 '+Math.round(p.energy)+' / '+p.a.stamina+(pct<25?' · 능력 저하':'')+'</small>';}
function refreshMarket(t){const round=t.w+t.l+t.d;if(t.marketRound===round)return;t.marketRound=round;t.market=Array.from({length:3},()=>{const p=player(false,t.players.map(x=>x.number));p.price=Math.round(abilityPrice(p)*balance(t).hireFactor);return p;});save();}
function preGameEconomy(t){ensureClub(t);if(t.players.some(p=>p.contract===0)){toast('계약이 끝난 선수의 연봉을 재협상해 주세요.');go('finance');return false;}return true;}
const oldStart=startMatch;startMatch=function(){const t=team();if(!needsSetup(t)&&!live(t)&&!preGameEconomy(t))return;const before=t.match?.id;oldStart();if(t.match?.id!==before){for(const tm of [t,t.match.opp])tm.players.forEach(p=>p.energy=p.a.stamina);t.match.used=t.lineup.map(x=>x.id);t.match.subs=[];save();render();}};
let fatigueSnapshot=null;
function restoreAbilities(){if(!fatigueSnapshot)return;for(const [p,a]of fatigueSnapshot)p.a=a;fatigueSnapshot=null;}
function effective(p,k){if(k==='stamina')return p.a[k];const ratio=clamp(p.energy/p.a.stamina,0,1),mult=ratio>=.5?1:balance().fatigueFloor+(1-balance().fatigueFloor)*(ratio/.5);return Math.max(1,Math.round(p.a[k]*mult));}
const originalBuildMotion=buildMotion;buildMotion=function(m,e){originalBuildMotion(m,e);for(const move of e.fieldMoves){if(move.knots||e.bh)continue;const p=ply(tside(m,1-e.attack),move.id),dist=Math.hypot(move.to[0]-move.from[0],move.to[1]-move.from[1]);move.end=clamp(.22+dist/(70+p.a.speed*1.2)*.28,.29,.85);}};
const oldResolve=resolvePitch;resolvePitch=function(m){const t=team();fatigueSnapshot=[t,m.opp].flatMap(tm=>tm.players.map(p=>[p,p.a]));for(const [p,a]of fatigueSnapshot)p.a=Object.fromEntries(KEYS.map(k=>[k,k==='stamina'?a[k]:effective(p,k)]));let e;try{e=oldResolve(m);}finally{restoreAbilities();}const b=balance(t),at=tside(m,e.attack),df=tside(m,1-e.attack),deduct=(p,n)=>{if(p)p.energy=Math.max(0,p.energy-n);};if(e.pitchThrown)deduct(ply(df,e.pitcher),b.pitchCost);if(e.swing)deduct(ply(at,e.batter),e.inputCommand==='power'?b.powerCost:b.swingCost);for(const mv of e.moves){let d=0;for(let i=1;i<mv.points.length;i++)d+=Math.hypot(mv.points[i][0]-mv.points[i-1][0],mv.points[i][1]-mv.points[i-1][1]);deduct(ply(at,mv.id),d*b.runCost*.22);}for(const mv of e.fieldMoves)deduct(ply(df,mv.id),Math.hypot(mv.to[0]-mv.from[0],mv.to[1]-mv.from[1])*b.runCost);save();return e;};
reward=function(m){if(m.rewarded)return;const t=team(),b=balance(t);m.rewarded=true;const win=m.score[0]>m.score[1];if(win)t.w++;else if(m.score[0]<m.score[1])t.l++;else t.d++;t.trophies=t.w;t.offer=null;m.result=win?'승리':m.score[0]===m.score[1]?'무승부':'패배';const crowd=attendance(t),ticket=m.home===0?crowd*t.ticket:0,stores=m.home===0?crowd*t.facilities.filter(id=>['goods','restaurant','store'].includes(id)).length:0,reward=b.baseReward+m.score[0]*b.runReward+(win?b.winReward:0),salary=t.players.reduce((s,p)=>s+p.salary,0),maint=t.facilities.length*b.maintenance,total=reward+ticket+stores;
gain(t,total,'경기 수입 · '+m.result);const due=salary+maint+t.debt,paid=Math.min(t.funds,due);spend(t,paid,'급여·시설·미지급금 결산');t.debt=due-paid;m.reward=reward;m.finance={reward,ticket,stores,crowd,salary,maintenance:maint,paid,debt:t.debt,net:total-paid};
const welfare=t.facilities.filter(id=>FACILITIES.find(f=>f[0]===id)?.[4]==='복지').length;for(const p of t.players){settleContract26(t,p,m,welfare);p.fans=Math.max(0,p.fans+(win?3:0)+(t.facilities.includes('fans')?2:0));}if(t.debt)news(t,'급여·유지비 일부 미지급','미지급금 '+money(t.debt)+'가 다음 결산으로 이어집니다. 선수 애정도가 8 감소했습니다.');
if(r(m)<b.fanEventChance){const available=t.players.filter(p=>p.loyalty>0&&!p.exitPending26);if(available.length){const p=pick(m,available),events=[['팬 사인회에 끝까지 남음',18,2],['구장 주변 쓰레기 무단 투기',-22,-2],['기부 소식이 알려짐',25,3],['팬의 인사를 무시함',-18,-3],['어린이 팬에게 공을 선물함',20,2]],x=pick(m,events);p.fans=Math.max(0,p.fans+x[1]);p.loyalty=clamp(p.loyalty+x[2],0,100);m.clubEvent={player:p.name,text:x[0],fans:x[1]};news(t,p.name+' · '+x[0],'개인 팬 '+(x[1]>0?'+':'')+x[1]+' · 애정도 '+(x[2]>0?'+':'')+x[2]);if(p.loyalty===0)p.exitPending26=true;}}t.market=[];
t.history.unshift({id:m.id,opp:m.opp.name,score:m.score.slice(),result:m.result,coins:0,funds:reward,finance:clone(m.finance),bh:m.bh[0],pitches:m.pitches,events:clone(m.events),checks:clone(m.checks),innings:clone(m.innings),home:m.home,hits:m.hits.slice(),errors:m.errors.slice(),boneheads:m.bh.slice(),skipped:!!m.skipped,recap:clone(m.recap||{box:{},highlights:[],events:0}),subs:clone(m.subs||[]),at:Date.now()});t.history=t.history.slice(0,20);departUnhappy26(t);};

// Composite the final, body-specific assets once per visible pose, not per animation tick.
const charImages=[],charCache=new Map();let charsReady=false;
const SKINS=['#ffd3a5','#e9b383','#d79b6c','#b87a51','#8d583d','#624130'];
function charFrame(p,tm,mode='motion',row=1,col=0){const a=enrich(p).appearance,key=[p.id,p.number,tm.primary,tm.secondary,mode,row,col,JSON.stringify(a)].join('|');if(charCache.has(key))return charCache.get(key);
const out=CharacterRenderer.render({...a,mode,row,col,palette:{primary:COLORS[tm.primary][1],secondary:COLORS[tm.secondary][1],skin:SKINS[a.skin]}}),cv=canvasNew(out.canvas.width,out.canvas.height),g=cv.getContext('2d');g.imageSmoothingEnabled=false;g.drawImage(out.canvas,0,0);const f=out.face;
if(mode==='detail'){g.fillStyle=COLORS[tm.secondary][1];g.textAlign='center';g.font='36px NeoDunggeunmo';g.fillText(String(p.number),580,570);}
const stand=LAB_DATA.bodies[a.body].motion.frames[1][0].rect,result={...out,canvas:cv,body:a.body,standHeight:stand[3]-stand[1],anchorX:out.foot[0],anchorY:out.foot[1]};if(charCache.size>450)charCache.clear();charCache.set(key,result);return result;}

const oldSprite=sprite;
sprite=function(c,x,y,scale,tm,number=0,role='player',pose='idle',tick=0,id='',flip=false){if(role!=='player'||!charsReady)return oldSprite(c,x,y,scale,tm,number,role,pose,tick,id,flip);const p=tm.players?.find(p=>p.id===id)||tm.market?.find(p=>p.id===id)||tm.players?.find(p=>p.number===number)||demoPlayer;let row=1,col=0;const e=anim?.e,pt=anim?playProgress(anim.elapsed/anim.duration):0;
if(pose==='run'){row=3;col=2+Math.floor(tick/(220-effective(p,'speed')))%2;}else if(pose==='bat'){row=0;col=0;}else if(pose==='swing'){row=0;col=pt<.23?2:e?.inputCommand==='power'?4:3;}else if(pose==='pitch'){row=1;col=Math.min(4,Math.floor(pt/.22*5));flip=true;}else if(pose==='throw'){row=2;col=4;}else if(['glove','catcher'].includes(pose)){row=2;col=1;}else if(pose==='catch'){row=4;col=0;}else if(pose==='slide'){row=4;col=3;}else if(pose==='sad'){row=5;col=5;}else if(pose==='confused'){row=5;col=3;}else if(pose==='celebrate'){row=4;col=0;}
if(['bat','swing'].includes(pose))flip=p.hand==='좌타';const a=charFrame(p,tm,'motion',row,col),height=[45,57,50,52,49,57][a.body]*scale,s=height/a.standHeight;c.save();c.translate(Math.round(x),Math.round(y));c.fillStyle='#06241f65';c.beginPath();c.ellipse(0,2,12*scale,3*scale,0,0,Math.PI*2);c.fill();if(flip)c.scale(-1,1);c.imageSmoothingEnabled=false;c.drawImage(a.canvas,Math.round(-a.anchorX*s),Math.round(-a.anchorY*s),Math.round(a.canvas.width*s),Math.round(a.canvas.height*s));c.restore();};
const demoPlayer={id:'uniform-demo',name:'선수',number:10,a:{contact:50,power:50,eye:50,speed:50,sense:50,catch:50,throw:50,velocity:50,control:50,stamina:70},hand:'우타',appearance:{body:2,skin:0,hairColor:2,eyeColor:0,parts:{hair:-1,beard:-1,wear:-1,eyes:-1,nose:-1,brows:-1,mouth:-1}}};
function paintDetail(cv,p,tm){if(!charsReady)return;const a=charFrame(p,tm,'detail'),g=cv.getContext('2d');cv.width=240;cv.height=320;g.imageSmoothingEnabled=false;g.clearRect(0,0,240,320);g.fillStyle='#031b244a';g.beginPath();g.ellipse(120,306,55,8,0,0,Math.PI*2);g.fill();const s=300/1536;g.drawImage(a.canvas,120-a.foot[0]*s,306-a.foot[1]*s,a.canvas.width*s,a.canvas.height*s);}
portraitCanvases=function(){$$('canvas[data-portrait]').forEach(cv=>{const t=cv.dataset.side==='opp'?team()?.match?.opp:team();const p=t?.players?.find(p=>p.id===cv.dataset.portrait)||t?.market?.find(p=>p.id===cv.dataset.portrait);if(p){paintDetail(cv,p,t);if(cv.getBoundingClientRect().width<85){const a=charFrame(p,t,'detail'),g=cv.getContext('2d'),f=a.face;g.clearRect(0,0,240,320);g.drawImage(a.canvas,f[0]-f[2]*.45,f[1]-f[3]*1.05,f[2]*1.9,f[3]*2.85,0,0,240,320);}}});};
drawJersey=function(){const host=$('#jerseyPreview');if(!host)return;host.innerHTML='<div class="uniform-view"><canvas id="fittingPlayer" width="240" height="320" style="width:260px;height:347px;image-rendering:pixelated"></canvas><p>팀 유니폼</p></div>';paintDetail($('#fittingPlayer'),demoPlayer,{primary:previewColors[0],secondary:previewColors[1]});};
drawActorLabel=function(c,actor,labels){const text='#'+actor.p.number+' '+actor.p.name;c.save();c.font='11px Galmuri9';c.textAlign='center';const width=c.measureText(text).width+10,y=actor.y+12;c.fillStyle='#042034dd';c.fillRect(actor.x-width/2,y-9,width,15);c.fillStyle='#fff4d2';c.fillText(text,actor.x,y+2);c.restore();};
textAt=function(c,text,x,y,size=13,color='#fff',align='center'){c.fillStyle=color;c.textAlign=align;c.font=size+'px '+(size>=20?'NeoDunggeunmo':'Galmuri9');c.fillText(text,x,y);};
// Present attack closer to home plate; all positions, shadows and balls share one transform.
const fieldSource=drawField.toString().replace('c.imageSmoothingEnabled=false;drawStadium(c,900,530,time);','c.imageSmoothingEnabled=false;').replace('const actors=[];','c.save();const zoom=a===0&&!e?.contact?1.16:1;c.translate(450*(1-zoom),490*(1-zoom));c.scale(zoom,zoom);drawStadium(c,900,530,time);if(e?.arc>30&&e.target&&t>.22&&t<.56&&e.type!=="hr"){const u=clamp((t-.22)/.33,0,1);c.save();c.globalAlpha=.2+.7*u;c.strokeStyle="#ffe879";c.lineWidth=2;c.beginPath();c.ellipse(e.target[0],e.target[1],34-22*u,12-7*u,0,0,Math.PI*2);c.stroke();c.restore();}const actors=[];').replace('effectsForEvent(c,e,t,time);','effectsForEvent(c,e,t,time);c.restore();');
drawField=(0,eval)('('+fieldSource+')');

// Club screens reuse the approved stadium, locker room and training backgrounds.
buttonsNav=function(){const t=activeGame?team():null;$('#header').innerHTML='<div class="brand" data-action="home">해체해라</div>'+(t?'<nav>'+[['home','구단 홈'],['lineup','라인업'],['players','선수'],['growth','훈련'],['market','영입'],['facilities','시설'],['finance','재정'],['records','기록'],['settings','설정']].map(([s,l])=>'<button data-go="'+s+'" class="'+(s===screen?'active':'')+'" '+(screen==='match'&&!t.match?.paused&&!t.match?.done?'disabled':'')+'>'+l+'</button>').join('')+'</nav><div class="spacer"></div><div class="resource fund">'+money(t.funds)+'</div><div class="resource">🏆 '+t.w+'</div><button data-go="slots" class="small">저장 '+(data.current+1)+'</button>':'<div class="spacer"></div><span class="muted">진지한 야구, 이상한 선수들.</span>');};
const oldHome=homeArtworkHTML;homeArtworkHTML=function(t){return oldHome(t).replace('완료 보상 · 기본 1 + 우리 득점','자금으로 영입 · 시설 · 훈련').replace('<button data-go="settings">','<button data-go="market">＋ 선수 영입</button><button data-go="facilities">▦ 구단 시설</button><button data-go="finance">재정 · 계약</button><button data-go="news">▣ 구단 소식</button><button data-go="settings">');};
const oldPlayers=playersArtworkHTML;playersArtworkHTML=function(t){let html=oldPlayers(t);const p=ply(t,selection)||t.players[0];return html.replace('평범한 선수도, 특별한 이야기를 만듭니다.','체형: '+LAB_DATA.bodies[p.appearance.body].name).replace(statBars(p),statBars(p)+energyHTML(p)+'<div class="profile-meta"><span>개인 팬 '+p.fans+'</span><span>애정도 '+p.loyalty+'</span><span>경기 급여 '+money(p.salary)+'</span><span>계약 '+p.contract+'경기</span></div>');};
growthArtworkHTML=function(t){const p=ply(t,selection)||t.players[0];selection=p.id;return head('선수 성장','훈련시설을 갖춘 뒤, 자금으로 능력치를 올립니다.')+'<section class="scene-frame scene-training growth-layout"><div class="growth-player"><select id="growthPlayer">'+t.players.map(x=>'<option value="'+x.id+'" '+(p.id===x.id?'selected':'')+'>'+esc(x.name)+' #'+x.number+'</option>').join('')+'</select><canvas id="practiceCast" width="500" height="350"></canvas></div><section class="panel stack"><h2>'+esc(p.name)+' #'+p.number+'</h2>'+KEYS.map(k=>{const f=trainingFacility(k),price=costGrowth(p,k),has=t.facilities.includes(f[0]);return '<div class="trainingrow"><span>'+STATS[k]+'<small class="muted" style="display:block">'+(has?f[1]:f[1]+' 필요')+'</small></span><b>'+p.a[k]+' → '+(price?p.a[k]+1:p.a[k])+'</b><button class="small primary" data-v8="train" data-stat="'+k+'" '+(live(t)||!has||!price||t.funds<price?'disabled':'')+'>'+(price?''+money(price):'최대')+'</button></div>';}).join('')+'<p class="fund">보유 자금 '+money(t.funds)+'</p><button data-go="facilities">훈련시설 확인</button></section></section>';};
let facilityCategory='전체';
function facilitiesHTML(t){const b=balance(t),limit=5+(t.stadium-1)*3;return head('구단 시설','필요한 시설부터 선택하세요. 시설당 매 경기 유지비 '+money(b.maintenance))+'<div class="panel ops-banner"><span>경기장 <strong>'+t.stadium+'등급</strong></span><span>건물 <strong>'+t.facilities.length+' / '+limit+'</strong></span><span>좌석 <strong>'+spectators(t.stadium*200)+'</strong></span><button class="primary" data-v8="upgrade" '+(live(t)||t.stadium>=5?'disabled':'')+'>경기장 확장 · '+money(t.stadium*2500)+'</button></div><div class="facility-tabs" role="group" aria-label="시설 카테고리">'+['전체','훈련','복지','수익','팬'].map(k=>'<button data-facility-category="'+k+'" aria-pressed="'+(facilityCategory===k)+'" class="'+(facilityCategory===k?'primary':'')+'">'+k+' <small>'+FACILITIES.filter(f=>k==='전체'||f[4]===k).length+'</small></button>').join('')+'</div><div class="ops-grid">'+FACILITIES.filter(f=>facilityCategory==='전체'||f[4]===facilityCategory).map(f=>'<section class="panel facility"><span class="gold">'+f[4]+'</span><h2>'+f[1]+'</h2><p>'+f[2]+'</p><small class="muted">유지비 '+money(b.maintenance)+' / 경기</small><button data-v8="build" data-id="'+f[0]+'" '+(live(t)||t.facilities.includes(f[0])||t.facilities.length>=limit||t.funds<b.facilityPrice?'disabled':'')+'>'+(t.facilities.includes(f[0])?'✓ 운영 중':'건설 · '+money(b.facilityPrice))+'</button></section>').join('')+'</div>';}
function marketHTML(t){refreshMarket(t);return head('선수 영입','선수 '+t.players.length+' / 35 · 후보는 경기가 끝난 뒤 갱신됩니다.')+'<div class="scout-grid">'+t.market.map(p=>'<section class="panel"><canvas class="portrait" data-portrait="'+p.id+'"></canvas><h2>'+esc(p.name)+'</h2><p>'+LAB_DATA.bodies[p.appearance.body].name+' · '+p.hand+'</p>'+statBars(p)+'<p>경기 급여 '+money(p.salary)+' · 계약 '+p.contract+'경기</p><button class="primary" data-v8="hire" data-id="'+p.id+'" '+(live(t)||t.players.length>=35||t.funds<p.price?'disabled':'')+'>영입 · '+money(p.price)+'</button></section>').join('')+'</div>';}
function financeHTML(t){return head('재정과 선수 계약','연봉을 경기별로 나누어 지급합니다. 계약이 끝나면 재협상이 필요합니다.')+'<div class="panel ops-banner"><span>자금 <strong>'+money(t.funds)+'</strong></span><span>미지급금 <strong>'+money(t.debt)+'</strong></span><span>예상 홈 관중 <strong>'+spectators(attendance(t))+'명</strong></span><label>입장료 (원)<input id="ticketPrice" type="number" min="1000" max="50000" step="1000" value="'+ticketInput(t.ticket)+'"></label><button data-v8="ticket" '+(live(t)?'disabled':'')+'>입장료 저장</button></div><div class="grid2"><section class="panel"><h3>선수 연봉 협상</h3><p class="muted-note">애정도가 높으면 기준 요구액이 낮아집니다. 요구액의 80% 미만 제안을 반복하면 애정도가 내려가고, 경고 후 이적할 수 있습니다. 남은 선수가 12명이면 이적을 유예합니다.</p><table class="economy-table"><thead><tr><th>선수</th><th>급여 / 남은 경기</th><th>애정도</th><th>협상</th></tr></thead><tbody>'+t.players.map(p=>'<tr><td>'+esc(p.name)+'</td><td>'+money(p.salary)+' / '+p.contract+'</td><td>'+p.loyalty+'</td><td><button class="small" data-v8="negotiate" data-id="'+p.id+'" '+(live(t)?'disabled':'')+'>협상</button></td></tr>').join('')+'</tbody></table></section><section class="panel"><h3>수입 · 지출 내역</h3>'+t.ledger.slice(0,30).map(x=>'<p class="row between" style="padding:10px 0;border-bottom:1px solid #294c66"><span>'+esc(x.label)+'</span><b class="'+(x.amount>=0?'good':'bad')+'">'+(x.amount>=0?'+':'')+money(x.amount)+'</b></p>').join('')+(!t.ledger.length?'<p class="muted-note">아직 거래가 없습니다. 시작 자금으로 운영을 준비하세요.</p>':'')+'</section></div>';}
function newsHTML(t){return head('구단 소식','경기장 밖에서도 선수의 이야기는 계속됩니다.')+(t.news.length?t.news.map(x=>'<article class="panel news-card"><h3>'+esc(x.title)+'</h3><p>'+esc(x.text)+'</p></article>').join(''):'<section class="panel">아직 새로운 소식이 없습니다.</section>');}
function financeResult(m){const f=m.finance;if(!f)return '';return '<section class="panel stack" style="margin-top:18px"><h3>경기 결산</h3>'+[['경기·득점·승리 보상',f.reward],['입장권 ('+(m.home===0?'홈':'원정')+' · '+spectators(f.crowd)+'명)',f.ticket],['매장 수입',f.stores],['지급한 급여·유지비·미지급금',-f.paid],['이번 자금 변화',f.net]].map(([l,v])=>'<div class="row between"><span>'+l+'</span><b class="'+(v>=0?'good':'bad')+'">'+(v>=0?'+':'')+money(v)+'</b></div>').join('')+(f.debt?'<p class="bad">남은 미지급금 '+money(f.debt)+'</p>':'')+(m.clubEvent?'<p class="muted-note">구단 소식 · '+esc(m.clubEvent.player)+' '+esc(m.clubEvent.text)+' · 팬 '+m.clubEvent.fans+'</p>':'')+'</section>';}
const oldResult=resultArtworkHTML;resultArtworkHTML=function(){const m=team().match;return oldResult().replace('기본 1 + 득점 '+m.score[0],'경기·득점·승리 자금').replace(m.reward+' 코인',''+money(m.reward))+financeResult(m);};
const oldDugout=dugoutHTML;dugoutHTML=function(m,side,st){const tm=tside(m,side),p=st.attack===side?ply(tm,tm.lineup[st.order[side]].id):pitcher(tm);return oldDugout(m,side,st).replace('</div></aside>',energyHTML(p)+'</div></aside>');};
const oldMatchHTML=matchHTML;matchHTML=function(){return oldMatchHTML().replace('<button class="small" data-action="skip-match">','<button class="small" data-v8="sub-open" '+(anim||reaction||shiftLead?'disabled':'')+'>선수 교체</button><button class="small" data-action="skip-match">');};
const oldRender=render;render=function(){data.slots.forEach(ensureClub);if(['market','facilities','finance','news'].includes(screen)){document.body.classList.remove('in-game');document.body.dataset.screen=screen;buttonsNav();$('#app').innerHTML=({market:marketHTML,facilities:facilitiesHTML,finance:financeHTML,news:newsHTML})[screen](team());portraitCanvases();}else oldRender();if(['home','facilities','finance','market'].includes(screen)&&team()&&!needsSetup(team()))$('#app').insertAdjacentHTML('beforeend',budgetHTML(team()));if(screen==='settings')$('#app').insertAdjacentHTML('beforeend','<section class="panel settings-extra"><h3>시험 설정 · 미확정 수치</h3><p class="muted-note">가격·체력 소모·계약 규칙은 이번 플레이용 시험값입니다. 변경은 이 구단의 이후 행동부터 적용합니다. v09 전환 시 기존 급여도 한 번 재산정합니다. 이후 시험값 변경은 재협상·새 영입부터 적용됩니다. 시작 자금은 유지됩니다.</p><button data-v8="balance">수치 조정</button> <button data-v8="licenses">글꼴 라이선스</button><p class="tiny muted">저장칸은 이전 게임과 분리됩니다. v08·v09·v10 백업을 불러올 수 있습니다. v08은 조정된 운영비를 적용한 복사본으로 이어집니다.</p></section>');};

function substitute(t,outId,inId){const m=t.match;if(!m||m.done||anim||reaction||shiftLead)return '투구·연출이 끝난 뒤 교체해 주세요.';const i=t.lineup.findIndex(x=>x.id===outId),p=ply(t,inId);if(i<0||!p||t.lineup.some(x=>x.id===inId)||m.used.includes(inId))return '출전하지 않은 후보만 교체할 수 있습니다.';const old=ply(t,outId),pos=t.lineup[i].pos;t.lineup[i].id=inId;m.used.push(inId);m.subs.push({out:old.name,in:p.name,inning:m.inning,pos});if(attack(m)===0)m.bases=m.bases.map(id=>id===outId?inId:id);p.stats.games++;if(pos==='P')p.stats.appearances++;if(m.formation?.[outId])m.formation[inId]=m.formation[outId].slice();delete t.battingDraft;save();return '';}
function subDialog(){const t=team(),m=t.match;if(!m||m.done||anim||reaction||shiftLead)return toast('현재 플레이와 리액션이 끝나면 교체할 수 있습니다.');m.paused=true;render();note('경기 중 선수 교체','<p>나간 선수는 이번 경기에 다시 나올 수 없습니다. 타순과 수비 위치를 후보가 이어받습니다.</p><label>나갈 선수<select id="subOut" style="width:100%">'+t.lineup.map(x=>{const p=ply(t,x.id);return '<option value="'+p.id+'">'+esc(p.name)+' · '+x.pos+' · 체력 '+Math.round(p.energy)+'/'+p.a.stamina+'</option>';}).join('')+'</select></label><div class="sub-options">'+t.players.filter(p=>!m.used.includes(p.id)).map(p=>'<button data-v8="sub-in" data-id="'+p.id+'">'+esc(p.name)+' #'+p.number+energyHTML(p)+'<small>구속 '+p.a.velocity+' / 제구 '+p.a.control+' / 컨택 '+p.a.contact+'</small></button>').join('')+'</div>');save();}
function salaryAsk(p){return Math.max(3,Math.round(abilityPrice(p)*balance().salaryFactor*(1+(50-p.loyalty)/200)));}
function negotiate(p,amount){const t=team(),ask=salaryAsk(p);if(!Number.isInteger(amount)||amount<1||amount>10000)return '제안 급여는 1만~1억 원, 1만 원 단위입니다.';if(amount>=ask*.8){p.salary=amount;p.contract=Math.max(1,Math.round(balance().contractGames));p.lowOffers=0;p.loyalty=clamp(p.loyalty+(amount>=ask?4:-2),0,100);news(t,p.name+' 재계약','경기 급여 '+money(amount)+' · '+p.contract+'경기 계약');return '재계약했습니다.';}p.lowOffers++;p.loyalty=Math.max(0,p.loyalty-15);if(p.loyalty<=15&&p.lowOffers>=2){if(t.players.length>12){const replacement=t.players.find(x=>x.id!==p.id&&!t.lineup.some(z=>z.id===x.id));if(replacement){t.lineup.forEach(x=>{if(x.id===p.id)x.id=replacement.id;});t.players=t.players.filter(x=>x.id!==p.id);t.departed.push(p);delete t.battingDraft;selection=t.players[0].id;news(t,p.name+' 이적','반복된 낮은 제안으로 팀을 떠났습니다. 기존 누적 기록은 이적 명단에 보관합니다.');return p.name+' 선수가 이적했습니다.';}}news(t,p.name+' 이적 의사','선수단 최소 12명 보호로 이적을 유예했습니다. 재협상이 필요합니다.');}return '제안을 거절했습니다. 애정도 -15. 낮은 제안을 반복하면 이적할 수 있습니다.';}
document.addEventListener('click',ev=>{const tab=ev.target.closest('[data-facility-category]');if(tab){facilityCategory=tab.dataset.facilityCategory;render();return;}const el=ev.target.closest('[data-v8]');if(!el||el.disabled)return;ev.stopImmediatePropagation();const t=team(),a=el.dataset.v8,id=el.dataset.id,b=balance(t);if(['train','build','upgrade','hire','ticket','negotiate','offer','apply-balance'].includes(a)&&live(t))return toast('경기가 끝난 뒤 변경할 수 있습니다.');
if(a==='train'){const p=ply(t,selection),k=el.dataset.stat,price=costGrowth(p,k);if(price&&t.facilities.includes(trainingFacility(k)[0])&&spend(t,price,p.name+' '+STATS[k]+' 훈련')){p.a[k]++;if(k==='stamina')p.energy=p.a.stamina;toast(STATS[k]+' +1');}}
if(a==='build'){if(FACILITIES.some(f=>f[0]===id)&&!t.facilities.includes(id)&&t.facilities.length<5+(t.stadium-1)*3&&spend(t,b.facilityPrice,FACILITIES.find(f=>f[0]===id)[1]+' 건설'))t.facilities.push(id);}
if(a==='upgrade'){if(t.stadium<5&&spend(t,t.stadium*2500,'경기장 확장'))t.stadium++;else toast('확장 자금이 부족합니다.');}
if(a==='hire'){const p=t.market.find(p=>p.id===id);if(p&&t.players.length<35&&spend(t,p.price,p.name+' 영입')){p.number=Array.from({length:100},(_,i)=>i).find(i=>!t.players.some(x=>x.number===i));t.players.push(p);t.market=t.market.filter(x=>x.id!==id);selection=p.id;news(t,p.name+' 영입','새 선수가 팀에 합류했습니다.');toast('영입 완료 · #'+p.number);}}
if(a==='ticket'){const n=ticketFromInput($('#ticketPrice').value);if(Number.isInteger(n)&&n>=1&&n<=50)t.ticket=n;else toast('입장료는 1,000~50,000원, 1,000원 단위로 입력해 주세요.');}
if(a==='negotiate'){const p=ply(t,id);note(p.name+' · 연봉 협상','<p>기준 요구액: 경기당 '+money(salaryAsk(p))+' · 애정도 '+p.loyalty+'<br>계약기간 '+b.contractGames+'경기</p><label>제안 경기 급여 (원)<input id="salaryOffer" type="number" min="10000" max="100000000" step="10000" value="'+wonValue(salaryAsk(p))+'"></label><button class="primary" data-v8="offer" data-id="'+p.id+'">제안하기</button>');return;}
if(a==='offer'){const msg=negotiate(ply(t,id),salaryFromInput($('#salaryOffer').value));$('#dialog').close();toast(msg);}
if(a==='sub-open')return subDialog();if(a==='sub-in'){const error=substitute(t,$('#subOut').value,id);if(error)return toast(error);$('#dialog').close();toast('교체 완료 · 경기 재개를 눌러주세요.');}
if(a==='balance'){note('시험 수치 조정','<p>시작 자금은 지급된 기준값입니다. 나머지 항목은 이후 행동부터 적용됩니다.</p><table class="economy-table">'+Object.entries(b).map(([k,v])=>'<tr><td>'+BALANCE_LABELS[k]+(balanceUnit(k)>1?' (원)':'')+'</td><td><input data-balance="'+k+'" type="number" step="any" min="0" value="'+v*balanceUnit(k)+'" '+(k==='startFunds'?'readonly':'')+'></td></tr>').join('')+'</table><button class="primary" data-v8="apply-balance" '+(live(t)?'disabled':'')+'>설정 저장</button>');return;}
if(a==='apply-balance'){const next=Object.fromEntries($$('[data-balance]').map(x=>[x.dataset.balance,Number(x.value)/balanceUnit(x.dataset.balance)]));if(Object.values(next).some(v=>!Number.isFinite(v)||v<0||v>100000)||next.fatigueFloor>1||next.fanEventChance>1||next.salaryBonusChance>1||next.salaryBonusLoyalty>100||!Number.isInteger(next.salaryBonusLoyalty)||next.staminaCap<1||next.staminaCap>100||!Number.isInteger(next.staminaCap)||next.contractGames<1||next.contractGames>100||!Number.isInteger(next.contractGames))return toast('비율은 0~1, 성장 한도는 1~100, 계약 기간은 1~100 정수로 입력해 주세요.');t.balance=next;t.economyVersion=9;$('#dialog').close();}
if(a==='licenses'){note('글꼴과 출처','<div class="license-copy">'+esc(window.FONT_LICENSE_TEXT||'')+'</div>');return;}
save();render();},true);
// Discourage stale legacy free-recruit actions, without altering the old saved games.
document.addEventListener('click',ev=>{const el=ev.target.closest('[data-action]');if(['accept-offer','reject-offer','replace-player','train'].includes(el?.dataset.action)){ev.stopImmediatePropagation();toast('새 영입·훈련 화면을 이용해 주세요.');}},true);

const originalLoadV9=load;load=function(){
 if(!localStorage.getItem(KEY)){const raw=localStorage.getItem('haechehaera.integrated.v11.20260923')||localStorage.getItem('haechehaera.integrated.v10.20260923')||localStorage.getItem('haechehaera.integrated.v09.20260923')||localStorage.getItem('haechehaera.integrated.v08.20260923');if(raw){try{const copy=JSON.parse(raw);validateRoot(copy);copy.slots.forEach(ensureClub);if(copy.slots[copy.current]?.match&&!copy.slots[copy.current].match.done)copy.slots[copy.current].match.paused=true;localStorage.setItem(KEY,JSON.stringify(copy));}catch(e){runtimeErrors.push('이전 저장 복사 실패: '+e.message);}}}
 originalLoadV9();
};
async function bootIntegrated(){const loading=document.createElement('div');loading.className='loading8';loading.innerHTML='<div><h1>해체해라</h1><p>여섯 체형의 선수와 구장을 준비합니다…</p><small>첫 로딩 이후에는 인터넷 연결 없이 플레이할 수 있습니다.</small></div>';document.body.append(loading);try{await CharacterRenderer.init();for(let i=0;i<6;i++)charImages[i]=await CharacterRenderer.images(i);charsReady=true;load();data.slots.forEach(ensureClub);if(team())selection=team().players[0]?.id;screen='slots';save();await loadArtwork();render();lastFrame=performance.now();requestAnimationFrame(tick);}catch(e){runtimeErrors.push(String(e));loading.innerHTML='<p>준비 중 오류: '+esc(String(e))+'</p>';throw e;}finally{if(charsReady)loading.remove();}}
window.GameV08={snapshot:()=>({screen,team:team(),errors:runtimeErrors,anim:anim?{type:anim.e.type,elapsed:anim.elapsed,duration:anim.duration,resultShown:anim.resultShown}:null,reaction:reaction?{speaker:reaction.speaker,left:reaction.left,eventId:reaction.eventId}:null,charsReady}),balance:()=>balance(),testReport:null};
bootIntegrated();
